version: '3'
services:
  client:
    build:
      context: ./client
    command: npm start
    stdin_open: true
    tty: true
    volumes:
      - ./client/:/usr/app/
      - /usr/app/node_modules
    ports:
      - "9010:3000"
    restart: always

volumes:
  client:
